# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SaldoDeHoras' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SaldoDeHoras
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'

  target 'SaldoDeHorasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SaldoDeHorasUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
